### ISSUE TITLE
ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone.

### ISSUE THREAD

**Issue by 2jun0** [boostcampaitech5/level3_recsys_finalproject-recsys-03#138]
```
Traceback (most recent call last):
  File "/opt/ml/lv3-2/back/main.py", line 4, in <module>
    from src import api, db
  File "/opt/ml/lv3-2/back/src/api/__init__.py", line 3, in <module>
    from src.api import feedback, music, auth
  File "/opt/ml/lv3-2/back/src/api/music.py", line 7, in <module>
    music_service = MusicService()
  File "/opt/ml/lv3-2/back/src/services/music.py", line 20, in __init__
    self.playlist_id_ext = PlaylistIdExtractor(k=pl_k, is_data_pull=True)
  File "/opt/ml/lv3-2/back/src/infer/playlist.py", line 21, in __init__
    self.load_dataset()
  File "/opt/ml/lv3-2/back/src/infer/playlist.py", line 79, in load_dataset
    Repository(local_dir=self.DATA_PATH).git_pull()
  File "/opt/conda/envs/back/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/back/lib/python3.10/site-packages/huggingface_hub/repository.py", line 521, in __init__
    raise ValueError("If not specifying `clone_from`, you need to pass Repository a valid git clone.")
ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone.
```

**Comment by kCMI113** [comment]
데이터 클론 안 받으셔서 그렀습니다~

**Comment by 2jun0** [comment]
하하하 감사합니다
